version: '2'

services:
  pop3:
    build:
      context: .
    ports:
      - "110:110"
      - "995:995"
    environment:
      - MAILNAME=example.com
      - MAIL_ADDRESS=admin@example.com
      - MAIL_PASS=password1234
